language: ruby

rvm:
  - 1.9.3

script:
  - cp config/database-example.yml config/database.yml
  - ./bin/bootstrap
  - bundle exec rake db:test:prepare VERBOSE=false
  - bundle exec rspec --backtrace --fail-fast --order random spec
