source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rack-contrib'
gem 'activerecord', :require => 'active_record'
gem 'activesupport'
gem 'pg'
gem 'omniauth', '~> 1.0.2'
gem 'omniauth-twitter', :git => 'git://github.com/arunagw/omniauth-twitter.git'
gem 'omniauth-facebook', '~> 1.2.0'
gem 'omniauth-contrib', '~> 1.0.0', :git => 'git://github.com/intridea/omniauth-contrib.git'
gem 'omniauth-oauth', '~> 1.0.0', :git => 'git://github.com/intridea/omniauth-oauth.git'
gem 'omniauth-origo', '~> 1.0.0.rc3', :git => 'git://github.com/origo/omniauth-origo.git'
gem 'pebblebed', :git => 'git://github.com/benglerpebbles/pebblebed.git'
gem 'yajl-ruby', :require => 'yajl'
gem 'dalli'
gem 'thor'
gem 'unicorn', '~> 4.1.1'
gem 'hupper', :git => 'git://github.com/origo/hupper.git'
gem 'petroglyph', :git => 'git://github.com/benglerpebbles/petroglyph.git'
gem 'bengler_test_helper',  :git => 'git://github.com/origo/bengler_test_helper.git'
gem 'rake'
gem 'rack', '~> 1.4', :git => 'git://github.com/rack/rack.git'
gem 'pingable'

group :development, :test do
  gem 'rspec', '~> 2.8'
  gem 'simplecov'
  gem 'rack-test'
  gem 'capistrano', '~> 2.9.0'
	gem 'capistrano-bengler', :git => 'git@github.com:origo/capistrano-bengler.git'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
