source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'activerecord', :require => 'active_record'
gem 'activesupport'
gem 'pg'
gem 'omniauth', '~> 1.0.0.rc2'
gem 'omniauth-twitter', :git => 'https://github.com/arunagw/omniauth-twitter.git'
gem 'omniauth-facebook', '~> 1.0.0.rc1', :git => 'https://github.com/mkdynamic/omniauth-facebook.git'
gem 'omniauth-contrib', '~> 1.0.0.rc2', :git => 'https://github.com/intridea/omniauth-contrib.git'
gem 'omniauth-oauth', '~> 1.0.0.rc2', :git => 'https://github.com/intridea/omniauth-oauth.git'
gem 'omniauth-origo', '~> 1.0.0.rc2', :git => 'https://github.com/origo/omniauth-origo.git'
gem 'pebblebed', :git => 'git@github.com:benglerpebbles/pebblebed.git'
gem 'yajl-ruby', :require => "yajl"
gem 'dalli'
gem 'rabl'
gem 'thor'
gem 'unicorn', '~> 4.1.1'
gem 'hupper', :git => 'git@github.com:origo/hupper.git'

group :development, :test do
  gem 'bengler_test_helper',  :git => "git@github.com:origo/bengler_test_helper.git"
  gem 'rake'
  gem 'rspec', '~> 2.7.0.rc1'
  gem 'simplecov'
  gem 'rspec-extra-formatters'
  gem 'rack-test'
  gem 'capistrano', '=2.8.0'
  gem 'capistrano-ext', '=1.2.1'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
  gem 'mock_redis'
end
