development:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/amedia-properties_development.log

staging:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/amedia-properties_staging.log

production:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/amedia-properties.log

test:
  gaia_endpoint_base: http://example.org/this_should_be_stubbed/
  logfile: log/amedia-properties_test.log

