---
development:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  log_path: log
  logstash:
    :type: :file
    :path: log/jsonevent.logz
    :sync: true

test:
  gaia_endpoint_base: http://example.org/this_should_be_stubbed/
  log_path: log
  logstash:
    :type: :file
    :path: log/jsonevent_test.logz
    :sync: true
