development:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/common_development.log
  log_path: log

staging:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/common_staging.log
  log_path: log

production:
  gaia_endpoint_base: http://admin.test.api.no/gaia/api/public/v1/
  logfile: log/common.log
  log_path: log

test:
  gaia_endpoint_base: http://example.org/this_should_be_stubbed/
  logfile: log/common.log
  log_path: log

