---
common: &common
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 5
  username: checkpoint
  reconnect: true

production:
  database: checkpoint_production
  password: 
  <<: *common

development:
  database: checkpoint_development
  password: 
  <<: *common

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  verbosity: quiet
