# Hanuman SOAP service configuration

common: &COMMON
  namespace: http://v2.webservice.hanuman.api.no/
  documentation: http://doc.api.no/snapshot/hanuman/webservicev2.html

development:
  logfile: log/hanuman_development.log
  <<: *COMMON

staging:
  logfile: log/hanuman_staging.log
  <<: *COMMON

production:
  logfile: log/hanuman_production.log
  <<: *COMMON

test:
  logfile: log/hanuman_test.log
  <<: *COMMON
